### ISSUE TITLE
Create a DI spec for our integration testing framework.

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#136]
Kevin Lin is working on an integration test framework for hourly builds.  We've currently set it up in AWS with some manually created virtual machines.  Would be much better to encode the architecture in a DI spec file, and run it that way.  (1) presumable it would be easier to manage and (2) it's really important to dogfood our own stuff, this is a great opportunity to do that.

**Comment by sirspinach** [comment]
migrated to https://trello.com/c/Dt717HMi/123-create-a-di-spec-for-our-integration-testing-framework
