### ISSUE TITLE
Swarm scheduling fluctuating when it can't resolve affinities

### ISSUE THREAD

**Issue by nlsun** [NetSys/quilt#137]
If we have 2 hosts, and say "red" and "blue" are exclusive, and we say 2 "red" and 2 "blue".

If 1 "red" goes on host1 and 1 "red" goes on host2 then there is no where for any "blue"s to go.

So if this happens then the scheduler seems to "overschedule" and might end up with 4 "red"s or something while no "blue"s will ever get scheduled. Then the scheduler will realize this and delete "red"s and try running "blue"s again. This will continue to loop.

**Comment by sirspinach** [comment]
migrated to https://trello.com/c/eOuhUC3C/122-swarm-scheduling-fluctuating-when-it-can-t-resolve-affinities
