### ISSUE TITLE
Graceful Handling of Master Cluster Membership Changes

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#14]
Add or removing a node from etcd is actually quite involved (requiring a certain number of manual steps).  As a result, DI simply blows everything away of the state of the world isn't as it would hope w.r.t the master nodes.  Really, we should support incremental changes of the etcd cluster by adding nodes slowly one at a time.

**Comment by secant** [comment]
Migrated to Trello.
https://trello.com/c/R0YkmBgN
