### ISSUE TITLE
Docker should not be accessible outside the cluster.

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#162]
Currently, from my laptop, I can run `docker -H tcp://<ip>:2375 ps` and get a response.  This is very very dangerous and shouldn't be possible given that we're apparently only binding to the private IP.  Need to investigate and fix this.

**Comment by mmussomele** [comment]
https://trello.com/c/nnZeRnhf/44-docker-should-not-be-accessible-outside-the-cluster#
