### ISSUE TITLE
Improve vagrant_api error messages

### ISSUE THREAD

**Issue by kklin** [NetSys/quilt#199]
In a lot the places where we shell out to run vagrant commands, if the command fails, we just return the error from the shell exec. However, those errors seem to be of the form `exit status 1`, so they don't tell us very much when they get printed out higher up in the call stack.

One thing we should do is have vagrant_api modify the error messages.
For example,
```
func (api *vagrantAPI) Up(id string) error {
	_, err := api.Shell(id, `vagrant --machine-readable up)`)
	if err != nil {
		return err
	}
	return nil
}
```
could become
```
func (api *vagrantAPI) Up(id string) error {
	_, err := api.Shell(id, `vagrant --machine-readable up)`)
	if err != nil {
		return fmt.Errorf("unable to boot vagrant machine %s: %s", id, err.Error())
	}
	return nil
}
```

Capturing `stderr` (e.g. http://stackoverflow.com/questions/18159704/how-to-debug-exit-status-1-error-when-running-exec-command-in-golang) may be more useful than using `err.Error()` in some places.

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/IZkGKSj4
