### ISSUE TITLE
nginx container not booting on Vagrant. 

### ISSUE THREAD

**Issue by yuenmeiwan** [NetSys/quilt#208]
Perhaps the container is too big? But try using google/pause and see if that works. I get the following error: `Failed to start container nginx: API error (500): No healthy node available in the cluster`. But I can ping the other VMs and leader selection works so I'm not entirely sure what the problem is.

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/5KxuO4Nq
