### ISSUE TITLE
Investigate the docker network plugin API

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#224]
In our system, unlike within the standard docker systems, the container networking may not be setup for a couple of seconds after a container is created.  This is somewhat of a problem as the container binary may startup expecting networking to be fully configured.  The proper solution is likely to plug into the docker networking API where, presumably, we can have the time to get things setup before the binary starts up.

https://github.com/docker/libnetwork/blob/master/docs/remote.md

**Comment by secant** [comment]
Migrated to Trello.
https://trello.com/c/yFWJ17U7
