### ISSUE TITLE
ci: Manually specify namespaces

### ISSUE THREAD

**Issue by kklin** [NetSys/quilt#227]
Manually specifying a prefix for the di-tester namespace is probably better than using the IP.
I haven't confirmed this, but I bet once everyone starts using local ci instances, we're going to
run into conflicts (because the IP address of the vagrant box will just be some private IP, picked
by Vagrant's dhcp server, that's the same for everyone).

**Comment by sirspinach** [comment]
migrated to https://trello.com/c/zRdaxIfR/118-ci-manually-specify-namespaces
