### ISSUE TITLE
Fix Loopback Warnings

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#229]
Currently when spark boots up it prints out this moderately scary warning:

```
16/03/13 03:42:32 WARN : Your hostname, accca41fc975 resolves to a loopback/non-reachable address: 10.0.11.2, but we couldn't find any external IP address!
```

The warning doesn't appear to affect anything, but it's a sign of a problem with our network configuration.  Should fix it.

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/m9Gmg0VR
