### ISSUE TITLE
Create a zookeeper spec file.  Compose with Spark for HA.

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#231]
Spark can take advantage of zookeeper for High availability.  This seems like a perfect first test case of DI composability.  We should develop a specification file that allows one to boot Zookeeper.  And then compose it with the spark specification file to give spark masters high availability.  Of course, this configuration should remain optional.

**Comment by mmussomele** [comment]
https://trello.com/c/MTitbc4G/39-create-a-zookeeper-spec-file-compose-with-spark-for-ha#
