### ISSUE TITLE
Container RAM/CPU targets

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#253]
We should be able to specify the RAM/CPU requirements/limits a particular container needs.  Syntax presumably should be similar to the machine RAM/CPU specifications.

This isn't strictly required for the paper, but would be nice to have.

**Comment by ejj** [comment]
This will be super useful for two things.  1) we want the ability to say "the cluster you're attempting to run this on is not big enough"  or alternatively make a recommendation o the number of VMs you'll need to pull of deploying a particular system. 2) Given a particular cluster we want the ability to say "Fill out excess capacity in the cluster with spark workers"

Both of these issues require knowledge of container sizes.

**Comment by akshayknarayan** [comment]
Additionally, 3) the ability to schedule containers on to VMs given their relative resource demands (Dominant Resource Fairness, etc)

**Comment by akshayknarayan** [comment]
Note: disk targets too.

**Comment by ejj** [comment]
So what we really need, is just a way to specify this stuff in the DSL.  For now, we shouldn't actually respect it in the dataplane as that would mean teaching updating our docker swarm code.  Once we've ripped out docker swarm and replaced it with our own scheduler, then we would implement in the dataplane.

**Comment by secant** [comment]
Migrated to Trello.
https://trello.com/c/8rjT2yCN
