### ISSUE TITLE
Error with tracebacks

### ISSUE THREAD

**Issue by kklin** [NetSys/quilt#279]
It'd make debugging easier.
Right now, if there's an error in DSL evaluation we either pass it on up to the caller, or use the error to create a new error that gets passed up.
We should, instead, return an error that encapsulates both errors so that we can build a traceback.

Thought needs to be put into how we should represent errors within our go code to best support this.

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/5InbWP1F
