### ISSUE TITLE
Cleanup AWS Size Descriptions

### ISSUE THREAD

**Issue by kklin** [NetSys/quilt#282]
Right now, many of the machine specifications in `provider/constraintConstants.go` can't actually boot DI. This is problematic when we create machines using constraints, e.g. `(machine (ram 1) (cpu 1))`, and we get a machine that can't actually boot DI.

**Comment by mmussomele** [comment]
https://trello.com/c/NM29OXp4/37-cleanup-aws-size-descriptions#
