### ISSUE TITLE
azure: Fix virtual networking setup

### ISSUE THREAD

**Issue by kklin** [NetSys/quilt#318]
Right now, Azure boots each machine in a completely new virtual network. This means private IP's aren't really good for anything, and all communication must happen over public IP's.

The fix for this is to create a single virtual network as part of the provider initialization, and then boot each machine inside that virtual network.

I spent some time playing around with this in the azurecli, and it seems that virtual networking may not be properly supported in the "classic manager" -- instead, we'll have to use the "azure resource manager".

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/wmKc8N62
