### ISSUE TITLE
gce: Figure out how to deal with network maximum

### ISSUE THREAD

**Issue by kklin** [NetSys/quilt#327]
GCE allows at most five networks. This is a problem because for each namespace, we create a new network.

It's worth noting that `gce.go` creates the network during its `Start()` function. This means that even if you're not using the `Google` provider, you'll create a network in gce if your gce keys are setup.

**Comment by sirspinach** [comment]
migrated to https://trello.com/c/ziNh4DDV/115-gce-figure-out-how-to-deal-with-network-maximum
