### ISSUE TITLE
Use a default disk size when none is specified

### ISSUE THREAD

**Issue by kklin** [NetSys/quilt#330]
Right now, if you boot an Amazon machine with no disk size specified, it'll try to boot it with a disk with 0Gb. Instead, we should boot it with some default size, maybe 32 gig.

I think the right place to do this is in the engine, in the translation from the dslMachine to dbMachine.

**Comment by akshayknarayan** [comment]
Looks like https://github.com/NetSys/quilt/commit/1ec5afd9f816e0711955cdbf55b239a6f972ea48 fixed this.

**Comment by mmussomele** [comment]
https://trello.com/c/PvcLhN66/33-use-a-default-disk-size-when-none-is-specified#

**Comment by mmussomele** [comment]
This is done.
