### ISSUE TITLE
Figure out how to handle multiple providers/regions

### ISSUE THREAD

**Issue by kklin** [NetSys/quilt#380]
Right now, we `list` all machines in all regions of all providers. This is necessary so that the infracontroller can properly kill machines (we need to check all providers/regions to figure out if there's any machines that aren't needed).
This seems excessive, especially as we support more and more regions and providers.

@ejj has proposed in the past that we have some kind of configuration file that specifies that Quilt should only operate on a certain selection of providers/regions.

**Comment by mmussomele** [comment]
https://trello.com/c/arxCCYoQ/31-figure-out-how-to-handle-multiple-providers-regions#
