### ISSUE TITLE
Update Language.md

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#390]
It's pretty darn out of date.

**Comment by akshayknarayan** [comment]
Specific areas for improvement (incomplete list)

QUILT_PATH section
- The current text makes it seem like QUILT_PATH need not be fully qualified - this should be clarified.

Connect section 
- What is the behavior if a label is connected, then a sub-label of that label is connected?
- Is the load balancing subsection accurate?

Placement section
- Needs an example of a machine rule
- What attributes may be specified in a machine rule?
- Can a machine rule also specify exclusivity?

**Comment by ejj** [comment]
On the issue of QUILT_PATH, that should be resolved as part of #364

**Comment by akshayknarayan** [comment]
Functions section

- enumeration of all built-ins and description of what they do
- importantly, difference between "define", "let", and "set" (potentially confusing)

**Comment by mmussomele** [comment]
https://trello.com/c/xudDTYBX/25-update-language-md#
