### ISSUE TITLE
Fully integrated Profiling

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#398]
We have some new profiling code checked into the repository, but you have to manually uncomment code to take advantage of it.  We should, instead, find some more convenient and fully integrated way to take advantage of it.  One option, btw, seems to be serving it over HTTP: https://golang.org/pkg/net/http/pprof/

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/YLQ2OQL0
