### ISSUE TITLE
Improve container garbage collection

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#402]
so 1) I'm not sure why we added container garbage collection in the first place.  My guess, is when we added it our disk size was tiny and we were running out of space or something.  We should look that up in the commit history ...

2) What we're doing now sucks.  If a container dies, we garbage collect it, losing it's log, and with them all of hope debugging it.  Much better to either, not do garbage collection at all or, as nlsun suggested, delay garbage collection for a while to make debugging easier.

**Comment by kklin** [comment]
Some context about swarm and stopped containers: https://github.com/docker/swarm/issues/2015.

**Comment by mmussomele** [comment]
https://trello.com/c/ydquHqIA/24-improve-container-garbage-collection
