### ISSUE TITLE
Better labeling

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#405]
So I'm not quite sure what the solution to this is, but here's the problem:  A large portion of our spec code does `map` to assign a list of containers each their own individual label.  The issue is that, from the network perspective, If labels are connected, you can only really access them through a vip -- they aren't individually addressable.  A simple case this breaks is spark, where the worker nodes really should be dealt with as a single unit, but the master really needs the ability to talk to them individually.  This seems fairly important.

**Comment by secant** [comment]
Migrated to Trello.
https://trello.com/c/v0IfSwXc
