### ISSUE TITLE
Much better error message for missing diskSize

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#415]
Currently we print the following if you don't provide a disk size
 ```
WARNING [May 28 16:56:39.064] Unable to boot machines on Amazon.       error=InvalidParameterValue: Value () for parameter groupId is invalid. The value cannot be empty
        status code: 400, request id:
 ```

This is *impossible* to debug.  Need something much better.  While we're at it, we should make sure we have good error messages for all the required machine attributes.

**Comment by kklin** [comment]
I swear this was fixed by setting a default disk size in 1ec5afd9f816e0711955cdbf55b239a6f972ea48 . . . Also, if you notice in shwang's output that errors, the machine log shows a DiskSize of 32.

**Comment by nlsun** [comment]
Oh wait...I just tested this out myself and it really is fixed. Pasting in the spec in question from slack.

```
(import "machines")
(define Namespace "shwang")
(define Provider "Amazon")
(define MasterCount 1)
(define WorkerCount (+ 1 MasterCount))
(machines.Boot
  MasterCount
  WorkerCount
  (list (provider Provider)
        (region "us-west-2")
        (ram 1)
        (cpu 1)
        (sshkey "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0Agm2LaUiZ+n+4HV9CGfHkhCXyzT+xx0/qe2FyX+ThS5dnQKvopO0iMGONnfKmuNGZgZVE/iFA2zbET3t8YcThFjInPeoCg2imahc7G3DlXO6LgkRUAFrgCEKmu84PesU5/zK7nR2CaVK5OK8ydDtTVLUt+qLNenJLkEM+Aqv+7TURIPjeHrZ12GgeNOJqrQfexOdS83Fz44vutyEBZCZJII0wgircNJa1tWSoFzVxl08OPdV8h6Zpv9F2+68+zH7wKwOfkdG0sezaYZ7V3AAb05aKFiQgBQTLZ8ixXmRWNddg43FrYnv6XXwdqYgFuF4HpGMMpmgHVDy/erOTjlN")
        ))
(define AdminACL (list "local"))
(label "red"  (makeList WorkerCount       (docker "nginx")))
(label "blue" (makeList (* 2 WorkerCount) (docker "nginx")))
(label "yellow" (makeList 1 (docker "nginx")))
(label "purple" (makeList 1 (docker "nginx")))
(connect (list 1024 65535) "red" "blue")
(connect (list 1024 65535) "blue" "red")
(place (labelRule "exclusive" "yellow") "purple")
```

**Comment by ejj** [comment]
So the real question then is what was that cryptic error message?

**Comment by kklin** [comment]
It actually reminds me of something nlsun saw before in scale testing.. although it resolved itself.
My theory was that there was race condition in the engine that initialized the Amazon provider before the namespace was set, thus causing the groupID to be the empty string. Don't know if that's actually possible with the way our code is written, though.

**Comment by secant** [comment]
Migrated to Trello.
https://trello.com/c/USdkuBmD
