### ISSUE TITLE
labeRule could be a bit more usable.

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#417]
It's really hard to make a list of labels exclusive with each other.  I think we could solve this by making the `labelRule` function take a list as an argument.  See the below slack conversation.

ethan [09:45] 
I don’t think this `labelRule` thing works very well (edited)

[09:45] 
let’s say I have a list of N labels

[09:45] 
and I want to make them all exclusive with each other

[09:46] 
I need to make a new larger label that includes them, and then make that larger label exclusive with itself (edited)

[09:46] 
which is kind of annoying, because that new larger label needs to be unique

[09:46] 
alternatively, of course, I could basically use a map to make each of the labels individually exclusive

[09:46] 
but it’s annoying

kklin [09:48] 
so I guess the question is whether `labelRule` is the right primitive

ethan [09:48] 
yeah

kklin [09:48] 
it’s correct ​_logically_​ I think

[09:48] 
but may be too primitive

ethan [09:48] 
correct

kklin [09:48] 
what do you think of making a stdlib function that does the map thing?

ethan [09:48] 
not sure

kklin [09:48] 
the alternative is baking in another built-in right?

ethan [09:49] 
I suppose

[09:49] 
I actually don’t have a proposal for something better

[09:49] 
I’m just saying we should think about this

kklin [09:49] 
sure

ethan [09:49] 
so one thing is, labelRule perhaps should be able to take a list of labels

[09:50] 
so you could do `(placement (labelRule exclusive (list …)) (list …))` (edited)

[09:54] 
spark.Exclusive:

[09:54] 
 ```
(define (Exclusive sparkMap)
  (let ((exfn (lambda (x) (labelRule "exclusive" x)))
        (rules (map exfn (hmapValues sparkMap)))
        (plfn (lambda (x) (place x (hmapValues sparkMap)))))
    (map plfn rules)))
```

[09:55] 
tad painful

new messages
kklin [09:56] 
I don't see anything wrong with taking a list of labels

ethan [09:56] 
Cool

[09:56] 
I think that would clean it up a lot actually

[09:57] 
I’ll file an issue

**Comment by sirspinach** [comment]
Migrated to https://trello.com/c/DriRvPke/110-labels-could-be-more-usable.
