### ISSUE TITLE
cluster: Distinguish between missing and broken provider

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#428]
Currently, when cluster connects to a cloud provider, if it returns an error, we swallow it silently.  This is to avoid annoying warnings for cloud providers the user hasn't setup credentials for.

Unfortunately, when I was running GCE I got a _real_ error that was swallowed:
```
DEBUG [Jun  3 16:06:46.723] failed to start up gce network           error=googleapi: Error 400: Invalid value for field 'resource.name': 'Demo'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```
To notice this error, I had to turn on debug logging, which isn't for usability.  It would be much better if we could somehow distinguish between "this provider isn't configured" and "I had an error connecting".  The former should be silent, the latter should be logged.  Perhaps, we need some "providerExists" function or something.

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/IBVSNygg
