### ISSUE TITLE
DI Master should monitor minions

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#43]
We should implement a "ping" protocol by which the di master occasionally verify the minions are still up.

Initially this could be implemented as a simple protobufs Ping message which is responded to with a Pong message.  Though we'll want to get more sophisticated than this well.  For example, the minion could monitor the various infrastructure containers it boots to verify that they're alive as well.  If something fails irrecoverably, the minion could alert the master who can take appropriate steps.

**Comment by secant** [comment]
Migrated to Trello.
https://trello.com/c/xgVqA3hb
