### ISSUE TITLE
Handling of containers that listen on the same port

### ISSUE THREAD

**Issue by akshayknarayan** [NetSys/quilt#434]
https://github.com/NetSys/quilt/commit/09b4cbf267f497bb5c12f102ad48ad0d09ed4d4d deals with this by introducing a special case at the database level. This has the side effect that dsl.QueryPlacements() returns an incorrect result, that is, a list not containing these extra implicit placement constraints. This makes #433 show incorrect results.

This functionality should be implemented at the dsl level - when compiling a stitch the extra placement constraints to separate containers listening on the same port should be added as dsl.Placements.

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/qQQGDYst
