### ISSUE TITLE
Simplify the cluster management code

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#436]
In cluster.go the Run function and the newCluster function is way too complicated.  Basically it's overly general to support a feature, the ability to run multiple clusters, that we never actually implemented.  It could be simplified pretty dramatically and, at the same time, simplify the provider interface.

**Comment by ejj** [comment]
This is a *MESS*, it's causing us to be very slow when booting, and introducing subtle bugs.  Marking this high priority.

The other thing that we should fix is how the foreman interacts with the cluster too.  Not entirely clear that they should be separate code for one thing.  A big issue now is that the foreman doesn't know the best time to start.  It needs to wait until the first cluster run, but it doesn't know when that's happened.

**Comment by sirspinach** [comment]
migrated to https://trello.com/c/2dYY6vUQ/108-simplify-the-cluster-management-code
