### ISSUE TITLE
AWS Provider can choose unsupported instance types.

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#446]
When I ran a spec with `(ram 3) (cpu 1)` the AWS provider choose an instance type that it was unable to boot.  We should figure out why it wasn't able to boot that instance type, and remove all instances from the option list that will fail for the same reason.

**Comment by sirspinach** [comment]
migrated to https://trello.com/c/cgg9HlWP/107-aws-provider-can-choose-unsupported-instance-types
