### ISSUE TITLE
DSL panic with special provider variable name

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#447]
The following spec causes quilt to panic:

```
(define provider "Amazon")
(machine (provider provider))
```

It's fine if naming the variable "provider" isn't allowed (though why shouldn't it be?)  The real issue here is that we're panicing instead of politely returning an error.

**Comment by kklin** [comment]
Do languages usually allow variables to have the same name as built-ins? Seems messy..

Btw, whoever picks this up should fix the type-checking in `sizeImpl` while they're at it.

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/BJhZBvwJ
