### ISSUE TITLE
Ditch the select from functions in the DB

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#450]
In the database we have these SelectFrom functions that allow us to do arbitrarily complicated things in choosing a collection of rows from the database.  This functionality is rarely used and adds a bunch of ugly complex code to the database.  Much better to just have a `SelectALL` function that just does the simple thing necessary to get all rows from the DB.  This should be faster for the typical use case, and simplify the code significantly.

**Comment by mmussomele** [comment]
Migrated to trello.
