### ISSUE TITLE
Attempt to rewrite the DB using code generation

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#451]
The database is in this somewhat awkward position where there's a lot of boilerplate that could benefit from something like reflection, but it's performance sensitive enough that doing so isn't feasible.  A new approach would be to rely on code generation, possibly using the `text/template` package.  This could allow us to greatly simplify the code, probably get rid of awkward types like `row`, auto-generate unit tests improving coverage, and make the database quite a bit faster.  It's a non-trivial project, but given the importance of the DB, it seems worth it.

**Comment by mmussomele** [comment]
Migrated to trello.
