### ISSUE TITLE
Simplify Database Triggers and Alerts

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#452]
I think the database alerting system would be a lot simpler if we ditched the Conn.run() and instead made it the responsibility of Transact() to alert everyone concerned if something changed.  This would allow us to do a couple of things that would be pretty cool:

1) We could ditch the table seq and make it part of the transact function state (yay!)

2) The only reason we call row.equal() is to figure out if we need to update the table seq.  Instead we could have a "should alert" boolean in the transaction.  While should_alert is false, we could call row.equal() at the times that we do now, but once should_alert is true we would no longer have to. For most of our code, this would mean calling row.equal exactly once per transaction, saving us O(n) row.equal calls.  This would be such a huge savings, we could likely replace row.equal with reflect.DeepEqual() with no real performance penalty.  This would be a *HUGE WIN* from a correctness perspective as row.equal is super error prone.

**Comment by mmussomele** [comment]
Migrated to Trello.
