### ISSUE TITLE
All Stitch Specifications should be in the integration test

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#455]
Apparently somewhere along the line, we had completely broken the zookeeper stitch and not noticed.  This is because we're doing unit tests that verify the stitch executes properly, but not doing a proper end-to-end test to verify that things actually come up.

We should do this for all of the stitches we write -- it will be a good opportunity to test both the stitches and Quilt itself.

**Comment by secant** [comment]
https://trello.com/c/r4wtgorZ

**Comment by secant** [comment]
Migrated to Trello.
https://trello.com/c/r4wtgorZ
