### ISSUE TITLE
Mirror docker registry

### ISSUE THREAD

**Issue by ejj** [NetSys/quilt#88]
One of the master nodes should act as a mirror for the docker registries.  This should help us avoid downloading container images from every single node which needs them.  

https://github.com/docker/distribution/blob/master/docs/mirror.md

There are some subtleties here, specifically around how nodes figure out which node is running the registry.  If the master nodes are replaced, then each worker will have to be updated with the new registry mirror IP address.  One possible solution would be to fake out a registry.di address in /etc/hosts which the minions could update as needed.

**Comment by ZhongtianWang** [comment]
Migrated to https://trello.com/c/vXCZEdro
